language: rust

rust:
  - nightly

dist: trusty

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libavahi-compat-libdnssd-dev


script:
  - cargo build --verbose
  - cargo test --verbose --lib logs_to_file

env:
  global:
    - RUST_BACKTRACE=1

