[package]
name = "nslogger_client"
version = "0.1.0"
authors = ["Guillaume Godet-Bar <guillaume.godetbar@gmail.com>"]

[lib]
name="nslogger"
crate-type = ["lib"]
path = "src/lib.rs"

[dependencies]
async-dnssd = "0.3.0"
futures = "*"
tokio-core = "*"
mio  = "*"
bitflags = "*"
openssl = "*"
byteorder = "*"
chrono = "*"
log = "*"
cfg-if = "0.1"
sys-info = "*"

[dev-dependencies]
env_logger = "*"
