[package]
name = "nslogger_client"
version = "0.1.0"
authors = ["Guillaume Godet-Bar <guillaume.godetbar@gmail.com>"]

[lib]
name="nslogger"
crate-type = ["lib"]
path = "src/lib.rs"

[dependencies]
async-dnssd = "0.3.0"
futures = "0.1.14"
tokio-core = "0.1.8"
mio  = "0.6.9"
bitflags = "0.9.1"
openssl = "0.9.14"
byteorder = "1.0.0"
chrono = "0.4.0"
log = "0.3.8"
cfg-if = "0.1"
sys-info = "0.4.1"

[dev-dependencies]
env_logger = "*"
